// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxaruccliqcjogwbunhc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4YXJ1Y2NsaXFjam9nd2J1bmhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2NjY3NDUsImV4cCI6MjA3NTI0Mjc0NX0._hCdm75gMASohpfPRnRqg5gOxTQ6-_vuZNwLtaATA-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});